name: Publish Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate docs
        uses: phpDocumentor/phpDocumentor@master

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          message: ':memo: Updating docs'
